using Microsoft.EntityFrameworkCore.Migrations;

namespace Entities.Migrations
{
    public partial class seedDatabase : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Albania')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Algeria')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Andorra')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Angola')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Antigua and Barbuda')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Argentina')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Armenia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Australia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Austria')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Azerbaijan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('The Bahamas')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Bahrain')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Bangladesh')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Barbados')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Belarus')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Belgium')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Belize')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Benin')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Bhutan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Bolivia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Bosnia and Herzegovina')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Botswana')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Brazil')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Brunei')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Bulgaria')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Burkina Faso')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Burundi')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Cambodia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Cameroon')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Canada')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Cape Verde')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Central African Republic')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Chad')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Chile')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('China')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Colombia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Comoros')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Congo, Republic of the')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Congo, Democratic Republic of the')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Costa Rica')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Cote d''Ivoire')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Croatia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Cuba')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Cyprus')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Czech Republic')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Denmark')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Djibouti')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Dominica')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Dominican Republic')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('East Timor (Timor-Leste)')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Ecuador')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Egypt')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('El Salvador')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Equatorial Guinea')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Eritrea')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Estonia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Ethiopia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Fiji')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Finland')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('France')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Gabon')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('The Gambia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Georgia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Germany')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Ghana')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Greece')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Grenada')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Guatemala')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Guinea')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Guinea-Bissau')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Guyana')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Haiti')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Honduras')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Hungary')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Iceland')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('India')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Indonesia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Iran')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Iraq')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Ireland')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Israel')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Italy')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Jamaica')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Japan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Jordan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Kazakhstan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Kenya')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Kiribati')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Korea, North')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Korea, South')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Kosovo')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Kuwait')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Kyrgyzstan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Laos')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Latvia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Lebanon')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Lesotho')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Liberia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Libya')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Liechtenstein')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Lithuania')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Luxembourg')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Macedonia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Madagascar')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Malawi')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Malaysia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Maldives')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Mali')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Malta')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Marshall Islands')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Mauritania')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Mauritius')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Mexico')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Micronesia, Federated States of')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Moldova')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Monaco')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Mongolia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Montenegro')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Morocco')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Mozambique')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Myanmar (Burma)')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Namibia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Nauru')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Nepal')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Netherlands')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('New Zealand')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Nicaragua')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Niger')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Nigeria')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Norway')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Oman')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Pakistan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Palau')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Panama')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Papua New Guinea')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Paraguay')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Peru')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Philippines')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Poland')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Portugal')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Qatar')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Romania')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Russia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Rwanda')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Saint Kitts and Nevis')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Saint Lucia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Saint Vincent and the Grenadines')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Samoa')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('San Marino')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Sao Tome and Principe')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Saudi Arabia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Senegal')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Serbia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Seychelles')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Sierra Leone')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Singapore')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Slovakia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Slovenia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Solomon Islands')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Somalia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('South Africa')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('South Sudan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Spain')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Sri Lanka')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Sudan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Suriname')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Swaziland')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Sweden')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Switzerland')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Syria')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Taiwan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Tajikistan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Tanzania')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Thailand')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Togo')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Tonga')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Trinidad and Tobago')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Tunisia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Turkey')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Turkmenistan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Tuvalu')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Uganda')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Ukraine')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('United Arab Emirates')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('United Kingdom')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('United States of America')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Uruguay')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Uzbekistan')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Vanuatu')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Vatican City (Holy See)')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Venezuela')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Vietnam')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Yemen')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Zambia')");
            migrationBuilder.Sql("INSERT INTO Countries (Name) VALUES('Zimbabwe')");
            migrationBuilder.Sql("INSERT INTO Cities (Name,CountryId) VALUES('Madrid',(SELECT Id FROM Countries WHERE NAME = 'Spain'))");
            migrationBuilder.Sql("INSERT INTO Tournaments (Name, CountryId) VALUES('La Liga',(SELECT Id FROM Countries WHERE NAME = 'Spain'))");

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM Countries");
            migrationBuilder.Sql("DELETE FROM Cities WHERE NAME = 'Madrid'");
            migrationBuilder.Sql("DELETE FROM Tournaments WHERE NAME = 'La Liga'"); 
        }
    }
}
